from datetime import datetime
from typing import Optional, List, Dict, Any
from enum import Enum
from pydantic import BaseModel, Field
from bson import ObjectId


class PyObjectId(ObjectId):
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        if not ObjectId.is_valid(v):
            raise ValueError(f"Invalid ObjectId: {v}")
        return ObjectId(v)

    @classmethod
    def __get_pydantic_json_schema__(cls, schema: Dict[str, Any], model_type) -> Dict[str, Any]:
        schema.update(type="string")
        return schema


# ─── Enums ────────────────────────────────────────────────────────────────────
class EventCategory(str, Enum):
    work = "work"
    personal = "personal"
    health = "health"
    learning = "learning"
    social = "social"
    other = "other"


class CognitiveLoadLevel(str, Enum):
    creative = "creative"  # Sketching, brainstorming
    technical = "technical"  # CAD, BIM, coding
    administrative = "administrative"  # Portfolio, emails
    analytical = "analytical"  # Research, planning


class MoodLevel(str, Enum):
    drained = "drained"
    unfocused = "unfocused"
    focused = "focused"
    energized = "energized"


class ExpenseCategory(str, Enum):
    food = "food"
    transport = "transport"
    materials = "materials"
    software = "software"
    entertainment = "entertainment"
    other = "other"


class EventStatus(str, Enum):
    scheduled = "scheduled"
    completed = "completed"
    skipped = "skipped"
    moved = "moved"


class EnergyLevel(str, Enum):
    low = "low"
    medium = "medium"
    high = "high"


class BehaviorAction(str, Enum):
    completed = "completed"
    skipped = "skipped"
    moved = "moved"
    created = "created"
    deleted = "deleted"


# ─── User Models ──────────────────────────────────────────────────────────────
class UserPersonaModel(BaseModel):
    wake_up_time: Optional[str] = None
    daily_goals: List[str] = Field(default_factory=list)
    procrastination_task: Optional[str] = None
    energy_pattern: Optional[str] = None
    preferred_workout_time: Optional[str] = None
    focus_hours: List[str] = Field(default_factory=list)
    ai_insights: Optional[str] = None
    monthly_budget: float = 0.0  # For CFO tracking
    hourly_rate: float = 0.0  # For opportunity cost calculation
    notification_cadence: List[int] = Field(default_factory=lambda: [30, 15, 5])  # Minutes before event
    adaptive_insights: List[str] = Field(default_factory=list)  # Generated by recursive learning
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class UserModel(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    open_id: str
    name: Optional[str] = None
    email: Optional[str] = None
    login_method: Optional[str] = None
    role: str = "user"
    google_access_token: Optional[str] = None
    google_refresh_token: Optional[str] = None
    google_token_expiry: Optional[int] = None
    google_calendar_id: Optional[str] = None
    wake_up_time: Optional[str] = None
    timezone: str = "UTC"
    onboarding_completed: bool = False
    last_briefing_date: Optional[str] = None
    persona: UserPersonaModel = Field(default_factory=UserPersonaModel)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    last_signed_in: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        populate_by_name = True
        json_schema_extra = {
            "example": {
                "_id": "507f1f77bcf86cd799439011",
                "open_id": "user123",
                "name": "John Doe",
                "email": "john@example.com",
                "timezone": "America/New_York",
                "onboarding_completed": True,
            }
        }


# ─── Event Models ─────────────────────────────────────────────────────────────
class EventModel(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    title: str
    description: Optional[str] = None
    start_time: int  # UTC milliseconds
    end_time: int    # UTC milliseconds
    timezone: str = "UTC"
    location: Optional[str] = None
    color: str = "#000000"
    category: EventCategory = EventCategory.other
    status: EventStatus = EventStatus.scheduled
    is_recurring: bool = False
    recurrence_rule: Optional[str] = None
    google_event_id: Optional[str] = None
    notes_content: Optional[str] = None
    ai_summary: Optional[str] = None
    energy_level: EnergyLevel = EnergyLevel.medium
    cognitive_load: CognitiveLoadLevel = CognitiveLoadLevel.administrative
    mood_level: MoodLevel = MoodLevel.focused
    is_focus_mode: bool = False  # Deep work block
    focus_mode_duration: Optional[int] = None  # Minutes
    proof_of_work_required: bool = False
    project_phase: Optional[str] = None  # Research, Design, Tech, Presentation
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        populate_by_name = True


class EventCreateRequest(BaseModel):
    title: str
    description: Optional[str] = None
    start_time: int
    end_time: int
    timezone: str = "UTC"
    location: Optional[str] = None
    color: str = "#000000"
    category: EventCategory = EventCategory.other
    energy_level: EnergyLevel = EnergyLevel.medium
    cognitive_load: CognitiveLoadLevel = CognitiveLoadLevel.administrative
    mood_level: MoodLevel = MoodLevel.focused
    notes_content: Optional[str] = None
    is_recurring: bool = False
    recurrence_rule: Optional[str] = None
    is_focus_mode: bool = False
    focus_mode_duration: Optional[int] = None
    project_phase: Optional[str] = None


class EventUpdateRequest(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    start_time: Optional[int] = None
    end_time: Optional[int] = None
    timezone: Optional[str] = None
    location: Optional[str] = None
    color: Optional[str] = None
    category: Optional[EventCategory] = None
    status: Optional[EventStatus] = None
    energy_level: Optional[EnergyLevel] = None
    cognitive_load: Optional[CognitiveLoadLevel] = None
    mood_level: Optional[MoodLevel] = None
    notes_content: Optional[str] = None
    reason: Optional[str] = None
    project_phase: Optional[str] = None


# ─── Note Models ──────────────────────────────────────────────────────────────
class NoteModel(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    event_id: Optional[str] = None
    title: str
    content: Optional[str] = None
    tags: List[str] = Field(default_factory=list)
    ai_tags: List[str] = Field(default_factory=list)
    category: Optional[str] = None
    is_pinned: bool = False
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        populate_by_name = True


class NoteCreateRequest(BaseModel):
    title: str
    content: Optional[str] = None
    event_id: Optional[str] = None
    tags: List[str] = Field(default_factory=list)


# ─── Behavior Event Models ────────────────────────────────────────────────────
class BehaviorEventModel(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    event_id: Optional[str] = None
    action: BehaviorAction
    original_start_time: Optional[int] = None
    new_start_time: Optional[int] = None
    reason: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        populate_by_name = True


# ─── Push Subscription Models ─────────────────────────────────────────────────
class PushSubscriptionModel(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    endpoint: str
    p256dh: str
    auth: str
    user_agent: Optional[str] = None
    is_active: bool = True
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        populate_by_name = True


class PushSubscriptionRequest(BaseModel):
    endpoint: str
    exponent_public_key: str
    auth: str


# ─── AI Conversation Models ───────────────────────────────────────────────────
class AIConversationModel(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    role: str  # "user" or "assistant"
    content: str
    metadata: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        populate_by_name = True


class AIMessageRequest(BaseModel):
    message: str
    timezone: str = "UTC"
    local_time: str
    day_of_week: str
    conversation_history: List[Dict[str, str]] = Field(default_factory=list)


class ParseEventRequest(BaseModel):
    text: str
    timezone: str = "UTC"
    local_time: str
    day_of_week: str


class ConflictDetectionRequest(BaseModel):
    start_time: int
    end_time: int
    exclude_event_id: Optional[str] = None


# ─── Voice Models ─────────────────────────────────────────────────────────────
class VoiceTranscriptionRequest(BaseModel):
    audio_url: str
    language: Optional[str] = "en"
    prompt: Optional[str] = None


# ─── Response Models ──────────────────────────────────────────────────────────
class ConflictResponse(BaseModel):
    has_conflicts: bool
    conflicts: List[EventModel] = Field(default_factory=list)
    suggestion: Optional[str] = None


class MorningBriefingResponse(BaseModel):
    briefing: str


class AIAnalysisResponse(BaseModel):
    insights: str


class ParseEventResponse(BaseModel):
    success: bool
    event: Optional[EventModel] = None
    error: Optional[str] = None


class TranscriptionResponse(BaseModel):
    text: str
    language: Optional[str] = None


# ─── Finance Models ───────────────────────────────────────────────────────────
class ExpenseModel(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    amount: float
    category: ExpenseCategory
    description: str
    ai_categorization: Optional[str] = None
    opportunity_cost_hours: Optional[float] = None  # Hours of work equivalent
    is_flagged: bool = False  # Flagged by AI as unnecessary
    ai_warning: Optional[str] = None  # Savage CFO warning
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        populate_by_name = True


class ExpenseCreateRequest(BaseModel):
    amount: float
    category: ExpenseCategory
    description: str


# ─── Mood & Energy Tracking Models ────────────────────────────────────────────
class MoodLogModel(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    event_id: Optional[str] = None
    mood_level: MoodLevel
    energy_level: EnergyLevel
    efficiency_score: float = 0.0  # 0-100
    notes: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        populate_by_name = True


class MoodLogRequest(BaseModel):
    mood_level: MoodLevel
    energy_level: EnergyLevel
    efficiency_score: Optional[float] = None
    notes: Optional[str] = None
    event_id: Optional[str] = None


# ─── Focus Mode Models ────────────────────────────────────────────────────────
class FocusModeSessionModel(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    event_id: str
    start_time: datetime = Field(default_factory=datetime.utcnow)
    end_time: Optional[datetime] = None
    duration_minutes: int
    check_in_interval: int = 25  # Pomodoro-style
    check_ins_completed: int = 0
    total_check_ins_required: int = 1
    proof_of_work_submitted: bool = False
    proof_of_work_image_url: Optional[str] = None
    is_completed: bool = False
    is_failed: bool = False  # Didn't check in
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        populate_by_name = True


class FocusModeCheckInRequest(BaseModel):
    proof_of_work_image_url: Optional[str] = None
    notes: Optional[str] = None


# ─── Weekly Autopsy Models ────────────────────────────────────────────────────
class WeeklyAutopsyModel(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    week_start: datetime
    week_end: datetime
    high_efficiency_blocks: List[Dict[str, Any]] = Field(default_factory=list)
    procrastination_patterns: List[Dict[str, Any]] = Field(default_factory=list)
    unnecessary_spending: List[Dict[str, Any]] = Field(default_factory=list)
    ai_generated_strategy: str = ""
    mood_time_correlation: Dict[str, Any] = Field(default_factory=dict)
    phase_efficiency: Dict[str, float] = Field(default_factory=dict)  # Research, Design, Tech, Presentation
    total_efficiency_score: float = 0.0
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        populate_by_name = True


# ─── Behavior Analysis Models ─────────────────────────────────────────────────
class BehaviorAnalysisModel(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    analysis_period_days: int = 7
    insights: List[str] = Field(default_factory=list)
    recommended_persona_updates: Dict[str, Any] = Field(default_factory=dict)
    new_notification_cadence: Optional[List[int]] = None
    cognitive_load_recommendations: Dict[str, str] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        populate_by_name = True


# ─── Response Models ──────────────────────────────────────────────────────────
class OpportunityCostResponse(BaseModel):
    expense_amount: float
    hours_of_work: float
    percentage_of_budget: float
    warning_message: str


class FinanceSummaryResponse(BaseModel):
    total_spent: float
    monthly_budget: float
    percentage_used: float
    burn_rate: float  # Per day
    days_until_budget_exhausted: float
    flagged_expenses: List[ExpenseModel] = Field(default_factory=list)


class EfficiencyMetricsResponse(BaseModel):
    average_efficiency_score: float
    peak_efficiency_time: Optional[str] = None
    peak_efficiency_mood: Optional[str] = None
    low_efficiency_time: Optional[str] = None
    low_efficiency_mood: Optional[str] = None
    mood_time_correlation: Dict[str, float] = Field(default_factory=dict)



# ─── Living JARVIS: Memory Engine Models ──────────────────────────────────────
class UserMemoryModel(BaseModel):
    """User's long-term memory journal — stores preferences, facts, and context"""
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    memory_type: str  # "preference", "fact", "pattern", "context"
    key: str  # e.g., "bank", "mood_pattern", "focus_hours"
    value: Any  # Flexible value storage
    context: Optional[str] = None  # Additional context
    importance_score: float = 0.5  # 0-1, used for retrieval ranking
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        populate_by_name = True


class ContextMemoryModel(BaseModel):
    """Contextual memory — stores recent interactions and state"""
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    context_type: str  # "voice_command", "event_created", "expense_logged", "mood_change"
    content: str  # The actual context/interaction
    related_entity_id: Optional[str] = None  # Event ID, expense ID, etc.
    relevance_score: float = 0.5  # 0-1, used for retrieval
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        populate_by_name = True


class FlexibleDataModel(BaseModel):
    """Universal flexible data storage — allows Gemini to create arbitrary tracking"""
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    category: str  # e.g., "water_intake", "coffee_logs", "mood_notes", "custom_tracking"
    data: Dict[str, Any]  # Arbitrary key-value pairs
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        populate_by_name = True


class PersonaConfigModel(BaseModel):
    """Adaptive persona — Jarvis's tone, behavior, and preferences"""
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    voice_tone: str = "savage"  # "savage", "supportive", "chill", "aggressive"
    verbosity: str = "concise"  # "brief", "concise", "detailed", "verbose"
    emoji_usage: bool = False
    system_prompt_override: Optional[str] = None  # Custom system prompt
    notification_style: str = "nudge"  # "nudge", "aggressive", "gentle", "silent"
    response_language: str = "en"
    adaptive_insights_enabled: bool = True
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        populate_by_name = True


class NotificationSettingsModel(BaseModel):
    """Dynamic notification settings — logic-based triggers, not hard-coded"""
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str
    notification_cadence: List[int] = Field(default=[30, 15, 5])  # Minutes before event
    enabled_days: List[str] = Field(default=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"])
    disabled_days: List[str] = Field(default_factory=list)  # e.g., ["Sunday"]
    quiet_hours_start: Optional[str] = None  # "22:00"
    quiet_hours_end: Optional[str] = None  # "08:00"
    weekly_autopsy_day: str = "Monday"
    weekly_autopsy_time: str = "09:00"
    behavior_analysis_day: str = "Monday"
    behavior_analysis_time: str = "10:00"
    custom_rules: Dict[str, Any] = Field(default_factory=dict)  # Arbitrary logic rules
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        populate_by_name = True


# ─── Request/Response Models for Living JARVIS ────────────────────────────────
class UpdateMemoryRequest(BaseModel):
    """Request to update user memory"""
    memory_type: str  # "preference", "fact", "pattern", "context"
    key: str
    value: Any
    context: Optional[str] = None
    importance_score: Optional[float] = None


class AskAnythingRequest(BaseModel):
    """Request to track arbitrary data or ask Jarvis to remember something"""
    category: str  # e.g., "water_intake", "coffee_logs"
    data: Dict[str, Any]  # Arbitrary data to store


class UpdatePersonaRequest(BaseModel):
    """Request to update Jarvis's persona"""
    voice_tone: Optional[str] = None
    verbosity: Optional[str] = None
    emoji_usage: Optional[bool] = None
    notification_style: Optional[str] = None
    response_language: Optional[str] = None


class UpdateNotificationSettingsRequest(BaseModel):
    """Request to update notification settings"""
    notification_cadence: Optional[List[int]] = None
    enabled_days: Optional[List[str]] = None
    disabled_days: Optional[List[str]] = None
    quiet_hours_start: Optional[str] = None
    quiet_hours_end: Optional[str] = None
    weekly_autopsy_day: Optional[str] = None
    weekly_autopsy_time: Optional[str] = None
    custom_rules: Optional[Dict[str, Any]] = None


class MemoryContextResponse(BaseModel):
    """Response containing relevant memory context"""
    memories: List[UserMemoryModel] = Field(default_factory=list)
    recent_context: List[ContextMemoryModel] = Field(default_factory=list)
    persona: Optional[PersonaConfigModel] = None
    notification_settings: Optional[NotificationSettingsModel] = None
